Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,15 +32,10 @@ jobs:
         set -e  # Fail the job if any command fails
         ssh -i private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=60 ubuntu@54.172.254.181 "mkdir -p /home/ubuntu/app"
 
-
     - name: Copy files to EC2 instance (to /home/ubuntu/app)
       run: |
+        set -e  # Fail the job if any command fails
         scp -i private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./your-app-directory/* ubuntu@54.172.254.181:/home/ubuntu/app
 
     - name: SSH into EC2 instance and restart the app
-      run: |
-        ssh -i private-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30 ubuntu@54.172.254.181 << 'EOF'
-          cd /home/ubuntu/app
-          docker-compose down
-          docker-compose up -d
-        EOF
+     
